# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
